temtem-wiki:
  project:
    version: ^project.version^

server:
  port: 8080
  servlet:
    context-path: /temtem-wiki

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temtem-wiki
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
